[package]
name = "shamrock"
version = "0.1.0"
authors = ["Nathan Knowler <nathan@knowler.me>"]
edition = "2018"

[dependencies]
structopt = "0.2.15"
tera = "0.11.20"
serde = "1.0.90"
serde_derive = "1.0.90"
heck = "0.3.1"
